[misc]
assume_yes = false
cleanup = true

[firmware]
upgrade = false

[docker]
enable_cleanup = false

[git]
repos = ["~/dotfiles"]

[commands]
"Manual binaries (lazygit, lazydocker, nvim)" = "bash ~/dotfiles/scripts/update-bins.sh"
